FROM nginx:alpine
MAINTAINER Chs97 chs97@w2fzu.com
COPY /opt/workdir/build /usr/share/nginx/html/

COPY /favicon.ico /usr/share/nginx/html/favicon.ico

COPY /nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]